name: Deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: registry.dev.smartnewservices.com.br
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: registry.dev.smartnewservices.com.br/excel-api-v2:${{ github.ref_name }}
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy-stg
        if: github.ref_name == 'dev'
        run: curl -X POST ${{ secrets.PORTAINER_STG_WEBHOOK_URL }}?SERVICE_TAG=${{ github.ref_name }}

      - name: deploy-prd
        if: github.ref_name == 'main'
        run: curl -X POST ${{ secrets.PORTAINER_PRD_WEBHOOK_URL }}?SERVICE_TAG=${{ github.ref_name }}
